### ISSUE TITLE
Add table of contents to readme

### ISSUE THREAD

**Issue by rk012** [varabyte/kobweb#136]
Add a table of contents to the top of the readme for easier navigation

---

* Add links to headings/subheadings
* Something like [this](https://github.com/Kotlin/kotlinx.serialization#table-of-contents) would probably work

**Comment by bitspittle** [comment]
Hey, thank you so much for not only checking out Kobweb but also taking the time to leave feedback. I really appreciate it!

I want you to know I absolutely agree with the spirit of this issue -- while the README is better than nothing, it's currently quite long and yet also not detailed enough in some ways. It's easy to feel lost.

This is something I'm taking active steps to fix.

So that said, I'm going to close this issue for the following reasons (**but I don't want you to feel like that should end the discussion if you think I'm missing something**):

* Github already supports TOC for every README, with a TOC button, although it's possible most people aren't aware of it.
  * Check out this screenshot from the link you shared:
  ![kotlinx-serialization-toc](https://user-images.githubusercontent.com/43705986/155029744-fcd12758-fee9-4512-9ca9-b81dfe2e3be9.png)

* You can check out issue #133 (which I just happened to open earlier today!).
  * This bug is essentially about moving most of the README over to my website. This will have many advantages, one of which is including a super convenient nav area that's always visible to the left of the content you are reading.
  * I'm hoping this will start taking place in the next two weeks, as opposed to one of those "coming soon (TM)" bugs.
