### ISSUE TITLE
Kobweb site export - gradle running for more than 47 minutes.

### ISSUE THREAD

**Issue by rajsingha** [varabyte/kobweb#354]
My system specs - 32GB ram, 2tb ssd, Ryzen 7 5800x, dedicated RX6550xt gpu.
Normally my android studio projects takes 5mins to build an apk, if codebase in 20million+ then maximum 8mins.
Even when running the kobweb site in devlopment mode its working fine able to run the site under 1mins.
But when Im trying to export the full stack site, gradle is running more than 47mins although my  AWS Jenkins stopped due to unable to process the build time. CPU metrics went to burstable zone.

My site is just single landing page with animations.

**Comment by bitspittle** [comment]
I'm sorry to hear that. My guess is your export got stuck on downloading a browser. For some people, it seems to happen.

Can you quit and restart the export? It should hopefully work pretty quickly at that point (and once it works, it will keep working because the browser is cached).

In a pinch, you could also set things up so that GitHub can export for you. See also: https://github.com/varabyte/kobweb#exporting-your-site-in-a-github-workflow

**Comment by bitspittle** [comment]
I'm going to mark this as closed because since 0.14.2 we should report information to make it clear where the bottleneck is.
