### ISSUE TITLE
Docs: fullstack export layout option is "kobweb", not "fullstack"

### ISSUE THREAD

**Issue by okarmazin** [varabyte/kobweb#596]
Command output:
```
>kobweb export --layout fullstack
Usage: kobweb export [OPTIONS]

Error: Invalid value for "--layout": invalid choice: fullstack. (choose from KOBWEB, STATIC)

```
kobweb version: `0.9.15`

Bad docs:
https://github.com/varabyte/kobweb?tab=readme-ov-file#exporting-and-running

**Comment by bitspittle** [comment]
Ah yes, you're right. I pushed these docs too early. kobweb-cli 0.9.16 will introduce this value. I probably screwed up because I'm so used to using the dev `kobweb` CLI build. Thanks for catching.

For now, use `--layout kobweb`

Maybe I'll put out 0.9.16 soon, which might be preferable to changing the README back since the `-- layout kobweb` name is really confusing.

**Comment by bitspittle** [comment]
Kobweb CLI 0.9.16 is out now. (Instructions to get latest here: https://github.com/varabyte/kobweb#update-the-kobweb-binary)

Thanks again for filing this, it got me to finally put out a new CLI version after a long time :)
