### ISSUE TITLE
Allow `kobweb run` to work in submodules of Gradle projects

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#73]
Given a project like:

```
root/
  gradlew
  a/
  b/
  c/d/e/kobweb-site/
```

this should work:

```
cd root/c/d/e/kobweb-site
kobweb run
```

Right now it doesn't because it's looking for gradlew in the current directory. Instead, we should crawl up to see if we can find gradlew in a parent directory instead of giving up immediately.

**Comment by bitspittle** [comment]
Fix will go out in kobweb 0.7.4

**Comment by Goregius** [comment]
Instead of searching upwards in the file path which is risky, say there is another gradle file outside of the project. It might be better to have a property in the configuration file listing the root directory, e.g. "../../". Alternatively have a kobwebRun gradle task which does the same thing as kobweb run.

**Comment by bitspittle** [comment]
By the way there is a gradle task - called kobwebStart, which you can run
manually if you want. (Be sure to run it as `kobwebStart -t`). Then run
`kobwebStop` when you want to shut down the server.
