### ISSUE TITLE
Using package structure for url path

### ISSUE THREAD

**Issue by PXNX** [varabyte/kobweb#86]
kt-files places in folder pages such as `pages/index.kt `or `pages/index.kt` result in url paths `/index` and `/about`.

What about having a subpackaged file such as `pages/bla/mypage.kt` to be found under the url path `/bla/mypage` ?

Currently this only results in a blank screen to be shown.

**Comment by bitspittle** [comment]
Nested URLs are definitely supposed to work. If they're not, I may have broke them at some point, or maybe it's a windows issue? I'll definitely take a look pretty soon.

This seems easy enough for me to set up on my own, but still - do you happen to have a project you'd be willing to share with me? Just in case the same project works for me and doesn't for you (e.g. because of an OS difference)

**Comment by bitspittle** [comment]
This will be fixed starting in Kobweb 0.7.11. I'll prioritize pushing out a release since this is a major bug.
