### ISSUE TITLE
parameterized pages

### ISSUE THREAD

**Issue by gabe97330** [varabyte/kobweb#96]
Seems useful to have a "generator" page composable that stands in for a set of similar page composable functions rather than a composable  for each. Something in the spirit of [parameterized tests in Junit5](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests)?

**Comment by gabe97330** [comment]
Dynamic routes seem equivalent to parameterized pages from a site user's perspective and honestly, I overlooked their significance . Parameterized pages could be interesting from a early binding time perspective e.g. for static export but are definitely not necessary.

**Comment by bitspittle** [comment]
I know this issue is crazy old and, if you're like me, you might even be looking at it now and barely remembering anything about it.

But I thought I'd ping it since I'm adding a new feature to Kobweb soon, which lets you explicitly add routes to get exported. This might be useful for creating specific instances of dynamic routes.

So for example, you can do this (in v0.15.3 whenever that goes out in the next few days):

```kotlin
kobweb {
   app {
     export {
       addExtraRoute("/users/0/posts/0", "posts/default-post.html")
   }
}
```

Between this and dynamic routes, I think we could probably do anything you originally intended with parameterized pages, so after 0.15.3 goes out, I'll probably close this old issue at long last :)

**Comment by bitspittle** [comment]
0.15.3 is out!
